spring:
  jpa:
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:h2:mem:youthcone21tdd
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console